# Copyright (C) 2024-2026 by the Turing @ DMF authors
#
# This file is part of Turing @ DMF.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Test mathrace_interaction.network.open_file_on_ssh_host."""

import pathlib
import tempfile
import typing

import mockssh
import paramiko
import pytest

import mathrace_interaction.network


@pytest.mark.parametrize("get_client", [
    lambda ssh_server: ssh_server.client("user"),
    lambda ssh_server: mathrace_interaction.network.get_ssh_client(
        ssh_server.host, "user", port=ssh_server.port, key_filename=ssh_server._users["user"][0])
])
def test_open_file_on_ssh_host_create_file(
    ssh_server: mockssh.Server, get_client: typing.Callable[[mockssh.Server], paramiko.SSHClient]
) -> None:
    """Test open_file_on_ssh_host by creating a file."""
    with tempfile.NamedTemporaryFile() as input_file, tempfile.NamedTemporaryFile() as output_file:
        text = "This is a text file generated by test_ssh_server_create_file"
        pathlib.Path(input_file.name).write_text(text)
        assert pathlib.Path(output_file.name).read_text() == ""
        # Copy the local input file to a remote output file via SFTP
        client = get_client(ssh_server)
        sftp = client.open_sftp()
        sftp.put(input_file.name, output_file.name, confirm=True)
        # Open the output file on the SSH server via SFTP and verify its content
        with mathrace_interaction.network.open_file_on_ssh_host(pathlib.Path(output_file.name), client) as stream:
            assert stream.read() == text
        # The SSH server is actually a mock one, which stores both input and output files on the same filesystem
        with mathrace_interaction.network.open_file_on_ssh_host(pathlib.Path(output_file.name), None) as stream:
            assert stream.read() == text
        assert pathlib.Path(output_file.name).read_text() == text
