version: 2
updates:
  - package-ecosystem: "docker"
    directory: "docker/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "pip"
    directory: "/turing"
    schedule:
      interval: "weekly"
      day: "monday"
