"""
Django settings for Turing project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import logging
import os
from decouple import config
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# SECURITY WARNING: keep the secret key used in production secret!
# Generate with the command
# python -c 'import random; result = "".join([random.choice("abcdefghijklmnopqrstuvwxyz0123456789!@#$^&*(-_=+)") for i in range(50)]); print(result)'

SECRET_KEY = config('SECRET_KEY', default="qf8ag)+du4akkax(sza43z55_#ih4!1@ej3i48cgn+027nx1mu")
DEBUG = config('DEBUG', default=False, cast=bool)
DEV_MODE = config('DEV_MODE', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=lambda v: [s.strip() for s in v.split(',')])
INTERNAL_IPS = config('INTERNAL_IPS', default='127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])
LOG_FILE = config('LOG_FILE', default="./django.log")
EMAIL_HOST = config('EMAIL_HOST', default=None)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=None)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=None)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)

REGISTRATION_OPEN = config('REGISTRATION_OPEN', default=False, cast=bool)

# Allenamento section
TURING_BASE_URL = config('TURING_BASE_URL', default='http://localhost:8000')
TURING_ADMIN_USER = config('TURING_ADMIN_USER', default='')
TURING_ADMIN_PASS = config('TURING_ADMIN_PASS', default='')
TURING_BOT_PASS = config('TURING_BOT_PASS', default='')
BOT_USERNAME = config('BOT_USERNAME', default='bot_driver')
ALLENAMENTI_DIR = config(
    'ALLENAMENTI_DIR',
    default=os.path.abspath(os.path.join(BASE_DIR, 'Allenamenti')),
)
TESTFILES_DIR = config(
    'TESTFILES_DIR',
    default=os.path.abspath(os.path.join(BASE_DIR, 'Testfiles')),
)

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    'engine.apps.EngineConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'simple_history'
]

if DEV_MODE:
    INSTALLED_APPS += ['debug_toolbar']

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

if DEV_MODE:
    MIDDLEWARE += [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        'debug_toolbar_force.middleware.ForceDebugToolbarMiddleware',
    ]


ROOT_URLCONF = 'Turing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'engine.context_processors.gare',
                'engine.context_processors.export_settings'
            ],
        },
    },
]

WSGI_APPLICATION = 'Turing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DB_NAME = config("RDS_DB_NAME", None)
DB_USER = config("RDS_USERNAME", "")
DB_PASSWORD = config("RDS_PASSWORD", "")
DB_HOSTNAME = config("RDS_HOSTNAME", "")
DB_PORT = config("RDS_PORT", default=5432, cast=int)

if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOSTNAME,
            'PORT': DB_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "engine.User"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Logging
class IPAddressFilter(logging.Filter):

    def filter(self, record):
        return True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'add_ip_address': {
            '()': 'Turing.settings.IPAddressFilter'
        }
    },
    'formatters': {
        'log_formatter': {
            'format': '{asctime} {name} {ip} {levelname} {message}',
            'style': '{',
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
            'filters': ['add_ip_address'],
            'formatter': 'log_formatter',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
    'root': {
        'level': 'DEBUG',
    },
}

# Login settings
LOGIN_REDIRECT_URL = "engine:index"
LOGOUT_REDIRECT_URL = "engine:index"

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'it'
TIME_ZONE = 'Europe/Rome'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# File uploads
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
